### ISSUE TITLE
Попытка реализовать Array.from

### ISSUE THREAD

**Issue by atmaSveRo** [atmaSveRo/Learn1#5]
Акифыч, не получилось у меня как с суммой или map, она явно более сложная, так как я понял, нужно учитывать массу типов переменных, я наколдовал только это, оно работает для строк:

const arrayFrom = (elem) => {
    const newArray = []
    if(typeof elem === "string") {
        for(let i = 0; i < elem.length; i++) {
            newArray.push(elem[i])
        }
    
    return newArray
    }
}

**Comment by Skolotsky** [comment]
Для строк ты молодец, так и надо было бы реализовать для строк. Можно конечно и оптимальнее, но для тебя это сейчас самый подходящий вариант.

**Comment by Skolotsky** [comment]
Вообще Issues - это скорее раздел, куда надо складывать задачки "что сделать" или "разобраться с ...", я не очень понимаю содержание этой issue. Не понятно какой вопрос надо решить, чтобы считать, что задача закрыта.

**Comment by atmaSveRo** [comment]
тогда пока закрою данный issue, а как доберусь до этого вопроса и нужна будет помощь, создам новый уже более конкретный
