### ISSUE TITLE
не разобрался с arguments

### ISSUE THREAD

**Issue by atmaSveRo** [atmaSveRo/Learn1#6]
Не знаю, нужно ли это сейчас, но в методе Array.from увидел, решил протестировать, но такое ощущение, что мне сначала надо задавать функцию, а в неё уже укладывать мой Array.from
сделал это, но, понятно, что не работает, поэтому последний тест такой дурацкий, хотел что нибудь без повторения

expect(testResults, arrayFrom((1, 2, 3), function()  {
        return arguments
    }), [1, 2, 3])

**Comment by Skolotsky** [comment]
конструкции (1, 2, 3) не существует

**Comment by Skolotsky** [comment]
подобные аргументы пишутся без скобок, просто один аргумент за другим. Подробнее об этом расписано в теории про расширенное использование функций, до которой ты не дочитал.

**Comment by Skolotsky** [comment]
Кажется можно закрывать проблему
